name: exc_1
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - openpyxl
  - pyxlsb
  - rapidfuzz
  - scipy
  # e outros pacotes
  - pip
  - pip:
    - -e .
    # outros pacotes pip que você usa
